### ISSUE TITLE
Parse Push Master Key Required issue

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-php-sdk#260] opened 2016-09-23 22:34 UTC
Testing this simple code from the php example..

```
$data = array("alert" => "Hi!");

// Push to Channels
ParsePush::send(array(
    "channels" => ["PHPFans"],
    "data" => $data
));

ParsePush::send($data, true);
```

or

```
$data = array("alert" => "Hi!");

// Push to Channels
ParsePush::send(array(
    "channels" => ["PHPFans"],
    "data" => $data
));

ParsePush::send($data, $useMasterKey = true);
```

Throws an error:

`Parse\ParseException: unauthorized: master key is required in Parse\ParseClient::_request() (line 375 of /libraries/parse-php-sdk/src/Parse/ParseClient.php).`

Heroku Logs:

Parse 2.2.21

```
Sep 23 15:25:53 aaa app/web.1:  error: Error generating response. { [Error: unauthorized: master key is required] status: 403, message: 'unauthorized: master key is required' } status=403, message=unauthorized: master key is required 
Sep 23 15:25:53 aaa app/web.1:  Error: unauthorized: master key is required 
Sep 23 15:25:53 aaa app/web.1:      at promiseEnforceMasterKeyAccess (/app/node_modules/parse-server/lib/middlewares.js:302:17) 
Sep 23 15:25:53 aaa app/web.1:      at /app/node_modules/parse-server/lib/PromiseRouter.js:137:22 
Sep 23 15:25:53 aaa app/web.1:      at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22) 
Sep 23 15:25:53 aaa app/web.1:      at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28 
Sep 23 15:25:53 aaa app/web.1:      at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9) 
Sep 23 15:25:53 aaa app/web.1:      at _combinedTickCallback (internal/process/next_tick.js:67:7) 
Sep 23 15:25:53 aaa app/web.1:      at process._tickDomainCallback (internal/process/next_tick.js:122:9) 
Sep 23 15:25:53 aaa heroku/router:  at=info method=POST path="/parse/push" host=laaa.herokuapp.com request_id=f44c53dc-1418-4158-bfa3-69ec93d57f13 fwd="" dyno=web.1 connect=0ms service=7ms status=403 bytes=574 
```

**Comment by jdalleniii** [comment] 2016-10-18 21:07
I have had the same experience with the simple code:

$user->save(true);

Traced this down to ParseObject.php, line 1137:

            if (count($requests) === 1) {
                $req = $requests[0];
                $result = ParseClient::_request(
                    $req['method'],
                    $req['path'],
                    $sessionToken,
                    json_encode($req['body']),
                    $useMasterKey
                );

$useMasterKey is false when viewed at line 1044.

**Comment by gateway** [comment] 2016-10-18 23:56
@jdalleniii I just gave up and switched to using CURL in php

quick example code

```
  // push end point  
  $url = $server . '/' . $path . '/push';
  // convert to json
  $_data = json_encode($data);
  // set up headers for curl request
  $headers = array(
      'X-Parse-Application-Id:' . $app_id,
      'X-Parse-Master-Key:' . $master_key,
      'X-Parse-REST-API-Key:' . $rest_key,
      'Content-Type: application/json'
  );
  
  // curl do its thing!
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_POST, true);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $_data);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($ch, CURLOPT_VERBOSE, true);
  curl_exec($ch);
  curl_close($ch); 
```

**Comment by jdalleniii** [comment] 2016-10-19 00:58
@gateway, 

Thanks for the code, I may do that if I need master key stuff to work in the future! Or I might figure out where the master key's being dropped.

My use case was a one-time migration of user images from Parse.com to AWS EC2 ParseServer, so I just pasted 'true' over '$useMasterKey'

**Comment by gateway** [comment] 2016-10-19 01:02
No problem here is what the payload looks like

```
        // push payload 
        $data = array(
            'channels' => ["$channel"],
            'type' => 'ios',
            'data' => array(
                'alert' => $text,
            ),
        );  
``` 

Of course in data => you can add more things in there.

I figured I would reply anyhow to let anyone else know thats stuck to use this workaround.. Ideally I would love to see the issue fixed.. I havent had time to see why yet.

**Comment by gateway** [comment] 2016-11-16 19:55
Anyone here on the PHP Team still doing work on fixes? @gfosco

**Comment by harish-bisht** [comment] 2016-11-23 11:16
This setting for push is working for me
ParsePush::send(array(
			  "where" => $pushquery,
			  "push_time" => $pushDate,
			  "data" => array(
			    "alert" => $pushMsg,
			    "sound" => 'default'
                   )
),$useMasterKey = true);

**Comment by shaunanderson** [comment] 2016-12-20 20:02
#260

**Comment by montymxb** [comment] 2016-12-22 01:37
Hey @gateway looks like you're calling ```ParsePush::send``` twice, it's quite possible the error you were getting is related to not passing a master key on the first call. Looks like it's been some time since you opened this, but if you could double check and see if that's the case perhaps we could close this (assuming it works)?

**Comment by jdalleniii** [comment] 2016-12-22 01:47
@montymxb, that's not the case when I try to update a user record. As I wrote above, the master key isn't used when we:
 $user->save(true);

**Comment by montymxb** [comment] 2016-12-22 22:09
Interesting, well looking at the lines you mentioned within ```ParseObject::deepSave``` and the only two methods that call it (```ParseObject::save``` and ```ParseObject::saveAll```) I don't believe there's an issue with passing a bool for master key use, at least not as far as I can see in the current sdk.

However, it's possible you have encountered an entirely independent issue, it all depends on your implementation. With that being said you should probably open up another issue, mostly due to the fact that ```ParsePush``` isn't a subclass of ```ParseObject``` and doesn't call it anywhere either; a similar issue regarding ```$useMasterKey``` but unrelated to this one. 

If you open another issue I would be more than willing to help you figure out where ```true``` is getting dropped. Hopefully we can sort yours out as well as this one.

**Comment by jdalleniii** [comment] 2016-12-22 22:33
We've worked around the issue, but I will surely create a new ticket if we need the functionality again - thanks!

**Comment by gateway** [comment] 2016-12-22 22:38
Curious question is anyone updating the PHP SDK anymore?

**Comment by gfosco** [comment] 2016-12-24 23:38
As of now, montymxb is an official maintainer and can approve changes. Sorry I haven't been able to spend time here, as I switched teams.

**Comment by montymxb** [comment] 2017-01-28 22:13
@gateway we're keeping the sdk up to date, we actually have a couple working on preparing pull requests now.

Separately I wanted to ask if there's anyone that has been able to find anything further regarding this issue, in particular anyone else who has been working with ```ParsePush``` already. At some point I intend to verify this myself but I haven't had a chance, yet. 

I want to find additional evidence as to what's going on here, in hopes that we can figure out what's going on for you guys. The only instance that comes to mind is another issue mentioning someone using push notifications is in #190 , but they appear to have it working in their instance.

**Comment by Stafox** [comment] 2017-01-30 18:15
So, I can confirm: to send push need to pass `true` for `$useMasterKey`.
Note: I use self hosted parse server, so to do any operation on parse server I set `$useMasterKey` to `true`

**Comment by montymxb** [comment] 2017-05-12 21:08
I'm going to go ahead and close this. 

Considering there are quite a few test cases for [ParsePush](https://github.com/parse-community/parse-php-sdk/blob/master/tests/Parse/ParsePushTest.php) it appears that, if this was an issue, it has since been resolved. There are tests that verify functionality with use of the master key and exception checking when the master key is missing. If anyone is still having a related issue we can reopen this if needed.

**Closed by montymxb** 2017-05-12 21:08 UTC
