### ISSUE TITLE
Connection timed out error only on PHP SDK

### ISSUE THREAD

**Issue by Akharote1** [parse-community/parse-php-sdk#310] opened 2017-05-06 08:28 UTC
Hello there,
I have a Parse Server setup on my Ubuntu VPS. I have been able to port my app perfectly from the hosted parse backend to the Parse Server. However the PHP SDK refuses to work as expected with my server.
Here is my test code (The placeholders have their proper values in my real code.):
```
<?php

define('PARSE_SDK_DIR', './Parse/' );
require 'autoload.php';

use Parse\ParseClient as ParseClient;
use Parse\ParseObject as ParseObject;
use Parse\ParseQuery as ParseQuery;
use Parse\ParseUser;
use Parse\ParseInstallation;
use Parse\ParseException;
use Parse\ParseCloud;


$app_id = 'myAppId';
$master_key = 'myMasterKey';
$rest_key = '';


try{
    ParseClient::initialize($app_id,null,$master_key);
    echo "Parse Client Initialized. <br>";
    ParseClient::setServerURL('http://myServerIP:1337','parse');
    echo "Parse Client URL Set. <br>";
    $query = new ParseQuery("_User");
    $object = $query->get("Fnx6wfiQSC");
    echo $object->getObjectId();
    }
catch (Parse\ParseException $ex){
    echo "Error while sending query.<br>";
    echo "Error code ".$ex->getCode().": ".$ex->getMessage()."<br>";
    }

try{
$testObject = new ParseObject("TestObject");
$testObject->set("foo", "bar");
$testObject->save();
echo $testObject->getObjectId();
}
catch (Parse\ParseException $ex){
    echo "Error while saving object<br>";
    echo "Error code ".$ex->getCode().": ".$ex->getMessage()."<br>";
}
?>
```
And here is the output:
```
Parse Client Initialized. 
Parse Client URL Set. 
Error while sending query.
Error code 7: Failed to connect to myServerIP port 1337: Connection timed out
Error while saving object
Error code 7: Failed to connect to myServerIP port 1337: Connection timed out
```

The server works just fine with the other SDKs but always times out on the PHP SDK. I am using Parse Server 2.3.8.
I hope someone can help me fix this problem as soon as possible.
Thanks in advance,
Aditya

**Comment by montymxb** [comment] 2017-05-06 15:38
@Akharote1 I would double check that you can reach the server from your VPS if you haven't already. It may sound silly, but it looks like you're simply unable to reach the server at the given port.

I would double check via **telnet** or the like that you can in fact reach the destination at the given port. Assuming you can reach it, I would double check the IP that you're passing. At some point along the way you might find an issue with the address you are passing. 

Also, have you tried passing a domain name instead? Just curious, as ultimately it _should_ make no difference whether you pass a domain or the resolved ip.

**Comment by mauriciord** [comment] 2017-05-09 12:57
Same problem here

**Comment by mauriciord** [comment] 2017-05-09 14:54
Any solution @Akharote1 ? I'm using parse server at Bitnami Google Cloud

**Comment by montymxb** [comment] 2017-05-09 16:58
@mauriciord I'm going to take a look at Bitnami and see what's going. I noticed quite a few of the links in their parse console are dead for one thing :/ .

Similar to what I mentioned above double check everything, especially the **port**. It's quite possible that they're just using **80**/**443** and not **1337** as you may be expecting.

**Comment by mauriciord** [comment] 2017-05-09 17:07
hey @montymxb i changed port at php sdk like this:
```php
ParseClient::setServerURL('https://domain.com.br:443','parse');
```
Just in the SDK. In server at Bitnami, still the same **1337**

Working 100% now :)

**Comment by montymxb** [comment] 2017-05-09 17:27
Glad it worked @mauriciord ! We've seen this in the past. Just a note that most of the hosted services are offered over **443** with SSL/TLS rather than **1337**; which is used internally more often than not.

Also since you're using the **https** protocol you can probably omit `:443`, given that **https** is routinely conducted over port **443** by default.
```php
ParseClient::setServerURL('https://domain.com.br','parse');
```

@Akharote1 given that you appeared to be using **1337** as well I would recommend switching to the port mentioned above as well and see if that doesn't fix your issue 👍 .

**Comment by mauriciord** [comment] 2017-05-12 16:49
Hey @montymxb , sorry to say that, but bad news :(
At this moment, it's not responding just in the PHP SDK, what can i do ?

**Comment by montymxb** [comment] 2017-05-12 20:46
@mauriciord hmmm. If you haven't already be sure to check the forward facing port (not sure if you just checked from the LAN via ssh as you mentioned), that is assuming the sdk isn't running on the same server.

If you're using a hosted service for parse you might want to open up a chat with them and see what's going on. If it's something you've set up yourself I would double check that parse-server is in fact running and is listening for requests. There could be a number of other issues, but I would start small and first verify your parse-server instance is in fact running, then moving on to checking that it is in fact listening on the expected ports. If you can account for one variable at a time you can gradually move up to where the php sdk cannot connect to the expected port. Accounting for possible issues one unit at a time will most likely allow you to pin down where the issue is, or at least will point you in the right direction.

If ultimately it seems like you're doing nothing wrong you'll probably want to have a chat with your shared hosting provider as mentioned above. Perhaps there's something that you need to account for when running on their servers? Their environment may have something configured (or not) that could be causing your connectivity issues.

**Comment by cinder92** [comment] 2017-05-13 17:38
hello i just receiving same error but for port 3001 #314

**Comment by montymxb** [comment] 2017-05-13 17:45
@cinder92 are you using a hosted parse service are did you set up your own?

**Comment by cinder92** [comment] 2017-05-13 17:47
@montymxb i'm using digital ocean, but is not the digital ocean server, because im using the same server for push notifications in another project.

**Comment by cinder92** [comment] 2017-05-13 17:50
at this code
```

function send(){
	// Push Notification Body
    $pushData = array(
        'alert' => "Titulo de la notificacion",
        'badge' => 'Increment',
        'content-available' => 1,
        'sound' => 'default',
        'notification' => [
            'notificationId' => 12345,
            'noticiaId' => 12345,
            'type' => 'news'
        ]
    );

    try {
        ParsePush::send(array(
            "channels" => ["debug"],
            "data" => $pushData
        ), true);
    } catch (Exception $ex) {
        die ("Notification Error code ".$ex->getCode().": ".$ex->getMessage()."<br>");
    }
}
```

i just receive this error

`Notification Error code 7: Failed to connect to 159.203.130.97 port 3001: Connection timed out`

**Comment by montymxb** [comment] 2017-05-13 17:51
Are you sure it's not port **443**, **80** or **1337**? Looking at digital ocean's setup you must have started up parse from the console. If so you probably got some message like `...running on port 1337`. That would be the port you will want to connect to.

**Comment by cinder92** [comment] 2017-05-13 17:51
Parse is running into port 3001

**Comment by mauriciord** [comment] 2017-05-13 17:54
@cinder92 Try `telnet DOMAIN 3001` from your machine and from the server that you're using the PHP SDK.

**Comment by cinder92** [comment] 2017-05-13 17:56
@mauriciord here is from my local machine, im going to talk with my server provider about it.

![captura de pantalla 2017-05-13 a la s 12 55 13](https://cloud.githubusercontent.com/assets/4725556/26027878/99824c8c-37db-11e7-897b-a6f605e53989.png)

**Comment by montymxb** [comment] 2017-05-13 18:04
@cinder92 interesting, so you definitely are running on **3001** then? That's quite odd, the php sdk should be able to connect readily to the service... I would contact your provider to see if there's something else going on.

If the IP above is correct (I would scrub that by the way...just in case someone else decides to poke your stuff) would you mind if I attempt a connection as well?

**Comment by mauriciord** [comment] 2017-05-13 18:08
Hey @cinder92 , probably it's in your shared hosting.
Talk with them to pass you a user SSH or talk them whats going on.
Try to put your code on Heroku, if works, sounds like your shared hosting is not allowing your site to connect with your parse server at port **3001**

> @mauriciord here is from my local machine, im going to talk with my server provider about it.
> ![](https://cloud.githubusercontent.com/assets/4725556/26027878/99824c8c-37db-11e7-897b-a6f605e53989.png)

**Comment by cinder92** [comment] 2017-05-13 18:11
@mauriciord yeah, thanks, i just created a ticket to check what's going on, i'm going to tell you if works.

**Comment by cinder92** [comment] 2017-05-13 18:12
@montymxb yep that ip is correct, you can try to make  a connection .

**Comment by cinder92** [comment] 2017-05-13 18:23
Sorry guys, there was a problem with my server provider, they just crated a rule in his firewall, and now all is working, thanks a lot!

**Comment by montymxb** [comment] 2017-05-13 18:28
@cinder92 glad to hear!

**Comment by montymxb** [comment] 2017-05-13 18:29
@mauriciord did you ever manage to resolve your issue by the way? You mentioned that the issue was stemming from your hosting? Was it something similar to what just popped up here?

**Comment by Akharote1** [comment] 2017-05-14 12:24
I have tried everything mentioned above. But have been unable to get it to work. I changed the port to another one and tried putting the domain in instead of the IP. It still did not have any affect.

**Comment by montymxb** [comment] 2017-05-15 18:43
@Akharote1 so you have tried verifying the connectivity via another application (such as **telnet**) mentioned above? If that indicates everything it running it's quite possible you're running into a similar firewall issue. 

I you haven't already I would contact the support for your hosting. Most of the possible issues are mentioned above, but not everything is covered. I'll be around to help if you still haven't gotten it after contacting your support.

**Comment by montymxb** [comment] 2017-07-15 00:19
@Akharote1 did you ever manage to resolve this by contacting your hosting? I haven't seen any activity here, so I'll close this out in about a week if I don't hear anything. Assuming it's been resolved.

**Closed** 2017-07-28 03:35 UTC
